---
version: '3.3'

volumes:
  pg-data:

services:
  # nerves_hub_api:
  #   image: nerves_hub_api:latest
  #   hostname: api.${DOMAIN}
  #   ports:
  #     - 4444:4444
  #   environment:
  #     HOST: api.${DOMAIN}
  #     PORT: 4444
  #     DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
  #     CA_HOST: ca.nerves-hub
  #     NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
  #     NERVES_HUB_DOMAIN: ${DOMAIN}
  #   volumes:
  #     - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  # nerves_hub_device:
  #   image: nerves_hub_device:latest
  #   hostname: device.${DOMAIN}
  #   ports:
  #     - 4445:4445
  #   environment:
  #     HOST: device.${DOMAIN}
  #     PORT: 4445
  #     DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
  #     CA_HOST: ca.nerves-hub
  #     NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
  #     NERVES_HUB_DOMAIN: ${DOMAIN}
  #   volumes:
  #     - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  nerves_hub_www:
    image: nerves_hub_www:latest
    hostname: ${DOMAIN}
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    environment:
      HOST: ${DOMAIN}
      PORT: 80
      DATABASE_URL: "ecto://db:db@postgres:5432/nerves_hub_web"
      SECRET_KEY_BASE: "03285X8MQ01dU8oO56pnpwgnL4eH70sTohga1bFb2mu/UKlkswnkGN9D/ZLLpgwX"
      LIVE_VIEW_SIGNING_SALT: "U7UeQwpezh0Fm5U7ZvuWm99ttXzuFC9TyoftI2Edmw4Yo0L7EKRtMvdm8UFJ7LS0"
      NERVES_HUB_CA_DIR: "/etc/ssl/nerveshub"
      NERVES_HUB_DOMAIN: ${DOMAIN}
      LOG_LEVEL: debug
    volumes:
      - ${PWD}/etc/ssl:/etc/ssl/nerveshub/

  postgres:
    image: postgres:10-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
      PGDATA: /data
    volumes:
      - pg-data:/pg-data
